---
title: "Transfer Entrop Flow Analysis"
author: "Mariel Jones"
date: "2024-08-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
fig_save = "./Figures/"
load_path = "./Data and Codes/Cleaned Data/"
```

```{r}
library(astsa)
library(dplyr)
library(xts)
library(lubridate)
library(RTransferEntropy)
library(tidyr)
library(ggplot2)
library(gridExtra)
library(forecastML)
library(cowplot)
library(reshape2)
```

### Data Import from EDI

```{r}
## Precipitation
precipURL  <- "https://pasta.lternet.edu/package/data/eml/edi/849/5/4f7e0b3029833c26d64fda3d23037d1d" 
precipInfile <- tempfile()
try(download.file(precipURL,precipInfile,method="curl"))
if (is.na(file.size(precipInfile))) download.file(precipURL,precipInfile,method="auto")

precip <-read.csv(precipInfile , header=F, skip=1, sep = ",", 
               col.names=c("TIMESTAMP", "South_PCP", "South_Flag"),check.names=TRUE)
               
unlink(precipInfile)
tmp3TIMESTAMP<-as.POSIXct(precip$TIMESTAMP,format="%Y-%m-%d %H:%M:%S")
# Keep the new dates only if they all converted correctly
if(nrow(precip[precip$TIMESTAMP != "",]) == length(tmp3TIMESTAMP[!is.na(tmp3TIMESTAMP)])){precip$TIMESTAMP <- tmp3TIMESTAMP } else {print("Date conversion failed for precip$TIMESTAMP. Please inspect the data and do the date conversion yourself.")}                                 
if (class(precip$South_PCP)=="factor") precip$South_PCP <-as.numeric(levels(precip$South_PCP))[as.integer(precip$South_PCP) ]               
if (class(precip$South_PCP)=="character") precip$South_PCP <-as.numeric(precip$South_PCP)
if (class(precip$South_Flag)!="factor") precip$South_Flag<- as.factor(precip$South_Flag)
                
# Convert Missing Values to NA for non-dates
precip$South_PCP <- ifelse((trimws(as.character(precip$South_PCP))==trimws("NA")),NA,precip$South_PCP)         
## 10 minute soil moisture
smURL  <- "https://pasta.lternet.edu/package/data/eml/edi/989/3/e25d4f15276a3158af412758502a59b0" 
smInfile <- tempfile()
try(download.file(smURL,smInfile,method="curl"))
if (is.na(file.size(smInfile))) download.file(smURL,smInfile,method="auto")

sm <-read.csv(smInfile, header=F, skip=1, sep=",", 
              col.names=c("TIMESTAMP", "S2S_UP_SH", "S2S_UP_DP", "S2S_MI_SH", 
                          "S2S_MI_DP", "S2S_LO_SH", "S2S_LO_DP", "S2N_UP_SH",     
                          "S2N_UP_DP", "S2N_MI_SH", "S2N_MI_DP", "S2N_LO_SH",     
                          "S2N_LO_DP"), check.names=TRUE)
               
unlink(smInfile)
tmp2TIMESTAMP<-as.POSIXct(sm$TIMESTAMP,format="%Y-%m-%d %H:%M:%S")
# Keep the new dates only if they all converted correctly
if(nrow(sm[sm$TIMESTAMP != "",]) == length(tmp2TIMESTAMP[!is.na(tmp2TIMESTAMP)])){sm$TIMESTAMP <- tmp2TIMESTAMP } else {print("Date conversion failed for sm$TIMESTAMP. Please inspect the data and do the date conversion yourself.")}                                                                    
                                
## Bog well WTE
bogURL  <- "https://pasta.lternet.edu/package/data/eml/edi/562/3/671f15337a677da71852de506a8d9b05" 
bogInfile <- tempfile()
try(download.file(bogURL,bogInfile,method="curl"))
if (is.na(file.size(bogInfile))) download.file(bogURL,bogInfile,method="auto")

bog <-read.csv(bogInfile, header=F,skip=1, sep=",",
               col.names=c("PEATLAND", "DATE", "WTE", "FLAG"), check.names=TRUE)
               
unlink(bogInfile)
if (class(bog$PEATLAND)!="factor") bog$PEATLAND<- as.factor(bog$PEATLAND)                                   
tmp1DATE<-as.Date(bog$DATE,format="%Y-%m-%d")
# Keep the new dates only if they all converted correctly
if(nrow(bog[bog$DATE != "",]) == length(tmp1DATE[!is.na(tmp1DATE)])){bog$DATE <- tmp1DATE } else {print("Date conversion failed for bog$DATE. Please inspect the data and do the date conversion yourself.")}
if (class(bog$WTE)=="factor") bog$WTE <-as.numeric(levels(bog$WTE))[as.integer(bog$WTE) ]               
if (class(bog$WTE)=="character") bog$WTE <-as.numeric(bog$WTE)
if (class(bog$FLAG)!="factor") bog$FLAG<- as.factor(bog$FLAG)
                
# Convert Missing Values to NA for non-dates
bog$WTE <- ifelse((trimws(as.character(bog$WTE))==trimws("NA")),NA,bog$WTE)  

# Select just the S2 watershed
bog = bog %>%
  filter(PEATLAND == 'S2')

## Lagg transition well WTE
laggwellURL  <- "https://pasta.lternet.edu/package/data/eml/edi/1126/1/2532f551e6e5a97aee8f140fb5da8a74" 
laggwellInfile <- tempfile()
try(download.file(laggwellURL,laggwellInfile,method="curl"))
if (is.na(file.size(laggwellInfile))) download.file(laggwellURL,laggwellInfile,method="auto")

laggwell <-read.csv(laggwellInfile, header=F, skip=1, sep=",", quot='"' ,
                    col.names=c("DateTime", "LoggerLevel", "LoggerTemp", "BP",     
                                "Precip", "bogwell", "well_elev", "well_name",     
                                "watershed", "year"), check.names=TRUE)
               
unlink(laggwellInfile)
              
tmp1DateTime<-as.POSIXct(laggwell$DateTime,format="%Y-%m-%d %H:%M:%S" )
# Keep the new dates only if they all converted correctly
if(nrow(laggwell[laggwell$DateTime != "",]) == length(tmp1DateTime[!is.na(tmp1DateTime)])){laggwell$DateTime <- tmp1DateTime } else {print("Date conversion failed for laggwell$DateTime. Please inspect the data and do the date conversion yourself.")}                                                                    
                                
## Streamflow
streamURL  <- "https://pasta.lternet.edu/package/data/eml/edi/573/1/2aca4b900546e80ed7dd409ff1ad9787" 
streamInfile <- tempfile()
try(download.file(streamURL,streamInfile,method="curl"))
if (is.na(file.size(streamInfile))) download.file(streamURL,streamInfile,method="auto")

stream <-read.csv(streamInfile, header=F, skip=1, sep=",",
                  col.names=c("Peatland", "DateTime", "Stage.ft", "Q.cfs", "q.mmh", "q.interval"),
                  check.names=TRUE)
               
unlink(streamInfile)
if (class(stream$Peatland)!="factor") stream$Peatland<- as.factor(stream$Peatland)                       
tmp1DateTime<-as.POSIXct(stream$DateTime,format="%Y-%m-%d %H:%M:%S")
# Keep the new dates only if they all converted correctly
if(nrow(stream[stream$DateTime != "",]) == length(tmp1DateTime[!is.na(tmp1DateTime)])){stream$DateTime <- tmp1DateTime } else {print("Date conversion failed for stream$DateTime. Please inspect the data and do the date conversion yourself.")}                                                                    

```

```{r}
#Data sets: stream (1962-2017), sm (2008-2023), precip (2011-2024), laggwell (2018-2020), bog (1961-2023)

#Resample precip to daily timestep
#round dates down to week
precip$day <- floor_date(precip$TIMESTAMP, "day")

#find mean sales by week
precip_daily = data.frame(precip %>%
  group_by(day) %>%
  summarize(South_PCP = sum(South_PCP)))

summary(precip_daily)
summary(bog)
```

```{r}
#Resample well data to daily timestep
#round dates down to week
laggwell$day <- floor_date(laggwell$DateTime, "day")

#find mean sales by week
laggwell_daily = data.frame(laggwell) %>%
  group_by(day, well_name) %>%
  summarize(well_elev = mean(well_elev))

head(laggwell_daily)
```
```{r}
#Melt the lagg data so there is a column per well
laggwell_melt = laggwell_daily %>%
  pivot_wider(names_from = 'well_name', values_from = 'well_elev')
head(laggwell_melt)
```

```{r}
#Resample soil moisture to daily timestep
#round dates down to week
sm$day <- floor_date(sm$TIMESTAMP, "day")

#find mean sales by week
sm_daily = data.frame(sm) %>%
  group_by(day) %>%
  summarise_all(mean) %>%
  select(-TIMESTAMP)

head(sm_daily)
```

```{r}
#Resample streamflow to daily timestep
#round dates down to week
stream$day <- floor_date(stream$DateTime, "day")

#find mean sales by week
stream_daily = data.frame(stream) %>%
  group_by(day) %>%
  summarize(qInterval = mean(q.interval)/10) 

head(stream_daily)
```


```{r}
#Merge into a dataframe by date and clip to full series
dat = merge(x = precip_daily, y = bog, by.x = "day", by.y = "DATE", all = TRUE)
dat = merge(dat, laggwell_melt, by = 'day', all = TRUE)
dat = merge(dat, sm_daily, by = 'day', how = 'outer', all = TRUE)
dat = merge(dat, stream_daily, by = 'day', how = 'outer', all = TRUE)
head(dat)
```


## Initial Plotting

```{r}
#Initial timeseries plots

#Precip
ggplot(data = dat, aes(x = day, y = South_PCP)) +
  geom_point(color = 'gray') +
  geom_line() +
  xlab('Date') + 
  ylab('Precipitation [cm]') + 
  theme(aspect.ratio = 0.3, 
        panel.background = element_blank())

#Bog WTE
ggplot(data = dat, aes(x = day, y = WTE)) + 
  geom_point(color = 'gray') + 
  geom_line() + 
  xlab('Date') + 
  ylab('Bog Water Table Elevation [m]') +
  theme(aspect.ratio = 0.3, 
        panel.background = element_blank())

#LAGG WTE
ggplot(data = dat) +
  geom_line(aes(x = day, y = KF42W), color = 'darkolivegreen1') + 
  geom_line(aes(x = day, y = KF43W), color = 'cadetblue1') + 
  geom_line(aes(x = day, y = KF45W), color = 'brown1') +
  geom_line(aes(x = day, y = S2S1), color = 'darkolivegreen') + 
  geom_line(aes(x = day, y = S2S2), color = 'cadetblue3') + 
  geom_line(aes(x = day, y = S2S3), color = 'brown') +
  xlab('Date') +
  ylab('Lagg Water Table Elevation [m]') + 
  theme(legend.position = 'none', 
        aspect.ratio = 0.3, 
        panel.background = element_blank())

#SOIL 
ggplot(data = dat) +
  geom_line(aes(x = day, y = S2S_UP_SH), color = 'darkolivegreen1') + 
  geom_line(aes(x = day, y = S2S_UP_DP), color = 'darkolivegreen1', linetype = 2) + 
  geom_line(aes(x = day, y = S2S_MI_SH), color = 'darkolivegreen3') +
  geom_line(aes(x = day, y = S2S_MI_DP), color = 'darkolivegreen3', linetype = 2) + 
  geom_line(aes(x = day, y = S2S_LO_SH), color = 'darkolivegreen') + 
  geom_line(aes(x = day, y = S2S_LO_DP), color = 'darkolivegreen', linetype = 2) +
  geom_line(aes(x = day, y = S2N_UP_SH), color = 'darkslategray1') + 
  geom_line(aes(x = day, y = S2N_UP_DP), color = 'darkslategray1', linetype = 2) + 
  geom_line(aes(x = day, y = S2N_MI_SH), color = 'darkslategray3') +
  geom_line(aes(x = day, y = S2N_MI_DP), color = 'darkslategray3', linetype = 2) + 
  geom_line(aes(x = day, y = S2N_LO_SH), color = 'darkslategray') + 
  geom_line(aes(x = day, y = S2N_LO_DP), color = 'darkslategray', linetype = 2) +
  xlab('Date') +
  ylab('Soil Moisture [m3/m3]') +
  theme(legend.position = 'none', 
        aspect.ratio = 0.3, 
        panel.background = element_blank()) 

#Streamflow
ggplot(data = dat, aes(x = day, y = qInterval)) +
  geom_point(color = 'gray') + 
  geom_line() + 
  xlab('Date') + 
  ylab('Streamflow [cm]') + 
  theme(aspect.ratio = 0.3,
        panel.background = element_blank())

```

## Clip to timescales for IT analysis

Leaving out the lagg water table levels, clip the data to the longest time length possible (~2012 - 2022)

```{r}
data_clipped = dat %>%
  select(-c('KF42W', 'KF43W', 'KF45W', 'S2S1', 'S2S2', 'S2S3', 'S6S1', 'S6S2', 'S6S3', 'S6N1', 'S6N2', 'S6N3'))

head(data_clipped)
```


```{r}
data = merge(data_clipped,
             data.frame(times = floor_date(seq(from = as.POSIXct('2011-02-03'), to = as.POSIXct('2017-02-28'), by = "day"), 'day')), 
             by.x = 'day', by.y = 'times', 
             all.y = TRUE)

head(data)
tail(data)
  
```
```{r}

#Precip
ggplot(data = data, aes(x = day, y = South_PCP)) +
  geom_point(color = 'gray') +
  geom_line() +
  xlab('Date') + 
  ylab('Precipitation [cm]') + 
  theme(aspect.ratio = 0.3, 
        panel.background = element_blank())

#Bog WTE
ggplot(data = data, aes(x = day, y = WTE)) + 
  geom_point(color = 'gray') + 
  geom_line() + 
  xlab('Date') + 
  ylab('Bog Water Table Elevation [m]') +
  theme(aspect.ratio = 0.3, 
        panel.background = element_blank())


#SOIL 
ggplot(data = data) +
  geom_line(aes(x = day, y = S2S_UP_SH), color = 'darkolivegreen1') + 
  geom_line(aes(x = day, y = S2S_UP_DP), color = 'darkolivegreen1', linetype = 2) + 
  geom_line(aes(x = day, y = S2S_MI_SH), color = 'darkolivegreen3') +
  geom_line(aes(x = day, y = S2S_MI_DP), color = 'darkolivegreen3', linetype = 2) + 
  geom_line(aes(x = day, y = S2S_LO_SH), color = 'darkolivegreen') + 
  geom_line(aes(x = day, y = S2S_LO_DP), color = 'darkolivegreen', linetype = 2) +
  geom_line(aes(x = day, y = S2N_UP_SH), color = 'darkslategray1') + 
  geom_line(aes(x = day, y = S2N_UP_DP), color = 'darkslategray1', linetype = 2) + 
  geom_line(aes(x = day, y = S2N_MI_SH), color = 'darkslategray3') +
  geom_line(aes(x = day, y = S2N_MI_DP), color = 'darkslategray3', linetype = 2) + 
  geom_line(aes(x = day, y = S2N_LO_SH), color = 'darkslategray') + 
  geom_line(aes(x = day, y = S2N_LO_DP), color = 'darkslategray', linetype = 2) +
  xlab('Date') +
  ylab('Soil Moisture [m3/m3]') +
  theme(legend.position = 'none', 
        aspect.ratio = 0.3, 
        panel.background = element_blank()) 

#Streamflow
ggplot(data = data, aes(x = day, y = qInterval)) +
  geom_point(color = 'gray') + 
  geom_line() + 
  xlab('Date') + 
  ylab('Streamflow [cm]') + 
  theme(aspect.ratio = 0.3,
        panel.background = element_blank())

```

## Aggregate to Monthly timescales

```{r}
#round dates down to week
data$month <- floor_date(data$day, "month")

#group by and summarize
data_means = data %>%
   group_by(month) %>%
   select(c(month, South_PCP, WTE, qInterval)) %>%
   summarize_all(mean, na.rm = TRUE) %>%
   rename(meanPrecip = South_PCP, meanWTE = WTE, meanQ = qInterval)

data_totals = data %>%
   group_by(month) %>%
   select(c(month, South_PCP, qInterval)) %>%
   summarize_all(sum, na.rm = TRUE) %>%
   rename(totPrecip = South_PCP, totQ = qInterval)

data_soils = data %>%
  mutate(S2S_SH = rowMeans(select(data, c(S2S_UP_SH, S2S_MI_SH, S2S_LO_SH)), na.rm = TRUE)) %>%
  mutate(S2S_DP = rowMeans(select(data, c(S2S_UP_DP, S2S_MI_DP, S2S_LO_DP)), na.rm = TRUE)) %>%
  mutate(S2N_SH = rowMeans(select(data, c(S2N_UP_SH, S2N_MI_SH, S2N_LO_SH)), na.rm = TRUE)) %>%
  mutate(S2N_DP = rowMeans(select(data, c(S2N_UP_DP, S2N_MI_DP, S2N_LO_DP)), na.rm = TRUE)) %>%
  group_by(month) %>%
  select(c(month, S2S_SH, S2S_DP, S2N_SH, S2N_DP)) %>%
  summarize_all(mean, na.rm = TRUE)
```

```{r}
#Merge all data together
data_monthly = merge(data_means, data_totals, by = 'month')
data_monthly = merge(data_monthly, data_soils, by = 'month')
summary(data_monthly)
```

## Monthly plots

```{r}
#Precip
p1 = ggplot(data = data_monthly) +
  geom_point(aes(x = month, y = meanPrecip, color = 'mean Precip')) +
  geom_line(aes(x = month, y = meanPrecip, color = 'mean Precip')) +
  geom_point(aes(x = month, y = totPrecip, color = 'total Precip')) +
  geom_line(aes(x = month, y = totPrecip, color = 'total Precip')) +
  xlab('Date') + 
  ylab('Precipitation [cm]') + 
  scale_color_manual(" ", values = c('gray', 'black')) + 
  theme(legend.position = 'top',
        aspect.ratio = 0.3, 
        panel.background = element_blank())

#Bog WTE
b1 = ggplot(data = data_monthly, aes(x = month, y = meanWTE)) + 
  geom_point(color = 'gray') + 
  geom_line(color = 'gray') + 
  xlab('Date') + 
  ylab('Bog WTE [m]') +
  theme(legend.position = 'top',
        aspect.ratio = 0.3, 
        panel.background = element_blank())


#SOIL 
s1 = ggplot(data = data_monthly) +
  geom_line(aes(x = month, y = S2S_SH, color = 'S2S SH')) +
  geom_line(aes(x = month, y = S2S_DP, color = 'S2S DP'), linetype = 3) + 
  geom_line(aes(x = month, y = S2N_SH, color = 'S2N SH')) +
  geom_line(aes(x = month, y = S2N_DP, color = 'S2N DP'), linetype = 3) + 
  geom_point(aes(x = month, y = S2S_SH, color = 'S2S SH')) +
  geom_point(aes(x = month, y = S2S_DP, color = 'S2S DP')) + 
  geom_point(aes(x = month, y = S2N_SH, color = 'S2N SH')) +
  geom_point(aes(x = month, y = S2N_DP, color = 'S2N DP')) + 
  xlab('Date') +
  ylab('Soil Moisture [m3/m3]') +
  scale_color_manual(" ", values =  c("darkolivegreen3", "darkolivegreen3", "royalblue", "royalblue")) + 
  theme(legend.position = 'top',
        aspect.ratio = 0.3, 
        panel.background = element_blank()) 

#Streamflow
q1 = ggplot(data = data_monthly) +
  geom_point(aes(x = month, y = meanQ, color = 'mean Q')) +
  geom_line(aes(x = month, y = meanQ, color = 'mean Q')) +
  geom_point(aes(x = month, y = totQ, color = 'total Q')) +
  geom_line(aes(x = month, y = totQ, color = 'total Q')) +
  xlab('Date') + 
  ylab('Streamflow [cm]') + 
  scale_color_manual(" ", values = c('gray', 'black')) +
  theme(legend.position = 'top',
        aspect.ratio = 0.3,
        panel.background = element_blank())

timeseries = plot_grid(p1, b1, s1, q1,
          labels = c('A', 'B', 'C', 'D'),
          label_size = 12,
          align="hv")

save_plot(paste0(fig_save, 'monthlydata_timeseries.pdf'), timeseries, base_height = 5)
save_plot(paste0(fig_save, 'monthlydata_timeseries.jpeg'), timeseries, base_height = 5)
timeseries

```



## Gap filling of soil moisture data

```{r}
data_monthly_nogaps = data_monthly %>%
  mutate(S2S_DP = na.approx(S2S_DP)) %>%
  mutate(S2S_SH = na.approx(S2S_SH)) %>%
  mutate(S2N_DP = na.approx(S2N_DP)) %>%
  mutate(S2N_SH = na.approx(S2N_SH))

summary(data_monthly_nogaps)
```

```{r}
ggplot(data = data_monthly_nogaps) +
  geom_line(aes(x = month, y = S2S_SH, color = 'S2S SH')) +
  geom_line(aes(x = month, y = S2S_DP, color = 'S2S DP'), linetype = 3) + 
  geom_line(aes(x = month, y = S2N_SH, color = 'S2N SH')) +
  geom_line(aes(x = month, y = S2N_DP, color = 'S2N DP'), linetype = 3) + 
  geom_point(aes(x = month, y = S2S_SH, color = 'S2S SH')) +
  geom_point(aes(x = month, y = S2S_DP, color = 'S2S DP')) + 
  geom_point(aes(x = month, y = S2N_SH, color = 'S2N SH')) +
  geom_point(aes(x = month, y = S2N_DP, color = 'S2N DP')) + 
  xlab('Date') +
  ylab('Soil Moisture [m3/m3]') +
  scale_color_manual(" ", values =  c("darkolivegreen3", "darkolivegreen3", "royalblue", "royalblue")) + 
  theme(legend.position = 'top',
        aspect.ratio = 0.3, 
        panel.background = element_blank()) 
```

## Information Theory Lagg Analysis

```{r}
# Transcribed functions from python
#Generate probability distribution
pdf = function(dat, bins = 15){
    #dat - data for which the pdf is to be derived
    #bins - number of histogram bins, bins are generally set to 15 given the results of
    #  optimization methods described in Ruddell & Kumar 2009
    h = hist(dat,  breaks = bins, plot = FALSE)
    return(h$density/(sum(h$density)))
}

 
#Calculate Entropy
entropy = function(dat){
    #dat - data for which the entropy is to be calculated
    probs = pdf(dat)
    vals = probs*log2(probs)
    h = -sum(vals, na.rm = TRUE)
    return(h)
}

```

```{r}
## Assume one immediate history
lagValue = 1

## Shift time series
lagTS = function(x, y, l){
  #Shift
  shiftedX = lag(x, n = l)
  shiftedY = lag(y, n = 0)
  
  #Merge into data frame and clip to non-na
  dat = data.frame(shiftedX, shiftedY) %>%
    drop_na()
  
  return(dat)
}
```

```{r}
#Calculate shifted values
shifted = lagTS(data_monthly$totPrecip, data_monthly$meanWTE, l = 3)

#Test plot lagged time series
b2 = ggplot() + 
  geom_point(data = data_monthly, aes(x = month, y = meanWTE), color = 'lightblue') + 
  geom_line(data = data_monthly, aes(x = month, y = meanWTE), color = 'lightblue') +
  geom_point(data = shifted, aes(x = data_monthly$month[1:70], y = shiftedY), color = 'royalblue') + 
  geom_line(data = shifted, aes(x = data_monthly$month[1:70], y = shiftedY), color = 'royalblue') +
  xlab('Date') + 
  ylab('Mean Bog WTE [m]') +
  theme(aspect.ratio = 0.3, 
        panel.background = element_blank())

p2 = ggplot() + 
  geom_segment(data = data_monthly, aes(x = month, y = totPrecip, xend = month, yend = totPrecip-totPrecip), color = 'gray') + 
  geom_point(data = data_monthly, aes(x = month, y = totPrecip), color = 'gray') + 
  xlab('Date') + 
  ylab('Total Precip [cm]') +
  theme(aspect.ratio = 0.3, 
        panel.background = element_blank())

lagged_timeseries = plot_grid(b2, p2, 
          labels = c('A', 'B'), 
          align = 'hv', 
          ncol = 1)

save_plot(paste0(fig_save, 'sample_laggedtimeseries.pdf'), lagged_timeseries, base_height = 5)
save_plot(paste0(fig_save, 'sample_laggedtimeseries.jpeg'), lagged_timeseries, base_height = 5)
lagged_timeseries

```
```{r}
te = transfer_entropy(shifted$shiftedX, shifted$shiftedY, lx = lagValue, ly = lagValue)
te
```

Full test of a year of lags

```{r}
#Take out the non-useful columns
data_monthly_reduced = data_monthly_nogaps %>%
  select(-c(month, meanPrecip, meanQ))

#Collect combinations of variables
combinations_x = c("totPrecip", "totPrecip", "totPrecip", "totPrecip", "totPrecip", "totPrecip", "totPrecip",
                   "meanWTE", "meanWTE", 
                   "S2S_SH", "S2S_SH" , "S2S_SH", 
                   "S2N_SH", "S2N_SH" , "S2N_SH", 
                   "S2S_DP", "S2S_DP", 
                   "S2N_DP", "S2N_DP", 
                   "totQ"
                   )
combinations_y = c("totPrecip", "meanWTE", "totQ",  "S2S_SH", "S2S_DP", "S2N_SH", "S2N_DP", 
                   "meanWTE", "totQ",
                   "S2S_SH", "S2S_DP", "totQ", 
                   "S2N_SH", "S2N_DP", "totQ", 
                   "S2S_DP", "totQ",
                   "S2N_DP", "totQ",
                   "totQ"
                   )
```


```{r}
#Lags to test
lags = 18
#Empty dataframe to contain te information
te_df = data.frame(matrix(ncol = 0, nrow = lags))


for(k in seq(1, 2)){
    #Reset
    te_results_for = c()
    
    #Assign variables
    #significant TE
    i = combinations_x[k]
    j = combinations_y[k]
    
    #all te and tcrit
    allte = c()
    tecrit = c()
    
    #Loop through lags
    for(l in seq(1, lags)){
      #Shift data
      shifted = lagTS(data_monthly[i], data_monthly[j], l = l)
      
      #Compute TE
      te = transfer_entropy(shifted[i], shifted[j], quiet = TRUE)
      
      #Add to full te list
      allte[l] = te$coef[1,1]
      tecrit[l] = mean(te$boot[1]) + 1.66*sd(te$boot[1])
      
      #If significant, add to other list, else na
      if(te$coef[1,4] < 0.05){
        te_results_for[l] = te$coef[1,1]
      }
      else{
        te_results_for[l] = NaN
      }
    }
    
    #Create and save TE plots
    lag_plot = ggplot() + 
            geom_point(aes(x = seq(1, lags), y = allte), color = 'royalblue') + 
            geom_line(aes(x = seq(1, lags), y = allte), color = 'royalblue') +
            geom_point(aes(x = seq(1, lags), y = tecrit), color = 'lightgray') + 
            geom_line(aes(x = seq(1, lags), y = tecrit), color = 'lightgray') +
            xlab('Lag') + 
            ylab('Transfer Entropy') +
            theme(aspect.ratio = 0.3, 
                  panel.background = element_blank())
    save_plot(paste0(fig_save, 'lag plots/', i, '->', j, '-lagg-series.pdf'), lag_plot, base_height = 2, base_asp = 3)
    save_plot(paste0(fig_save, 'lag plots/', i, '->', j, '-lagg-series.jpeg'), lag_plot, base_height = 2, base_asp = 3)
              
    #Assign to dataframe
    te_df[paste0(i, '->', j)] = te_results_for
}
```

```{r}
head(te_df)
```

```{r}
#Heat map plot

#Melt data
te_df['lag'] = seq(1, lags)
te_df_melt = melt(te_df, id.vars = 'lag')

#Plot
lag_heatmap = ggplot(te_df_melt, aes(lag, variable)) +
  geom_tile(aes(fill = value), color = 'lightgray', lwd = 0.5, linetype = 1) +
  geom_text(aes(label = round(value, 2)), size = 3, color ='white') +
  scale_fill_gradient("Transfer Entropy", low = "lightblue", high = "deepskyblue4", na.value = 'white')+
  theme(panel.background = element_blank()) + 
  xlab("Time Lag [months]") + 
  ylab(" ")

save_plot(paste0(fig_save, 'laggedheatmap.pdf'), lag_heatmap, base_height = 5, base_asp = 2)
save_plot(paste0(fig_save, 'laggedheatmap.jpeg'), lag_heatmap, base_height = 5, base_asp = 2)
lag_heatmap


```




